### ISSUE TITLE
DOMAIN NOT FOUND 

### ISSUE THREAD

**Issue by Pranav-Saraswat** [hkpeprah/git-achievements#6]
domain www.git-achievements.com was not found 
it shows me that domain is available for sale ..

**Comment by hkpeprah** [comment]
Sorry about that. This project hasn't really been touched since `2014`. I plan on re-writing it eventually, but my current domain focus (Embedded Software / C) is quite different from when I wrote this and things have changed a fair bit in the web space that I need to brush up on; as well as Github's API has changed.

**Comment by willtheorangeguy** [comment]
As of right now, the page redirects to a page to add a rather questionable extension: 
![msedge_E82biWnpsi](https://user-images.githubusercontent.com/18339050/181167546-f7180370-92aa-4883-95d0-34a27c735f0d.png)
